# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_android_affected import AdvisoryAndroidAffected

class TestAdvisoryAndroidAffected(unittest.TestCase):
    """AdvisoryAndroidAffected unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryAndroidAffected:
        """Test AdvisoryAndroidAffected
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryAndroidAffected`
        """
        model = AdvisoryAndroidAffected()
        if include_optional:
            return AdvisoryAndroidAffected(
                ecosystem_specific = vulncheck_sdk.models.advisory/eco_system.advisory.EcoSystem(
                    severity = '', 
                    spl = '', 
                    type = '', ),
                package = vulncheck_sdk.models.advisory/android_package.advisory.AndroidPackage(
                    ecosystem = '', 
                    name = '', ),
                ranges = [
                    vulncheck_sdk.models.advisory/android_range.advisory.AndroidRange(
                        events = [
                            vulncheck_sdk.models.advisory/android_event.advisory.AndroidEvent(
                                fixed = '', 
                                introduced = '', )
                            ], 
                        type = '', )
                    ],
                versions = [
                    ''
                    ]
            )
        else:
            return AdvisoryAndroidAffected(
        )
        """

    def testAdvisoryAndroidAffected(self):
        """Test AdvisoryAndroidAffected"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
