# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_sitecore import AdvisorySitecore

class TestAdvisorySitecore(unittest.TestCase):
    """AdvisorySitecore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisorySitecore:
        """Test AdvisorySitecore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisorySitecore`
        """
        model = AdvisorySitecore()
        if include_optional:
            return AdvisorySitecore(
                cve = [
                    ''
                    ],
                date_added = '',
                refs = [
                    ''
                    ],
                summary = '',
                summary_ja = '',
                title = '',
                title_ja = '',
                updated_at = '',
                url = ''
            )
        else:
            return AdvisorySitecore(
        )
        """

    def testAdvisorySitecore(self):
        """Test AdvisorySitecore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
