# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_nvd20_configuration import AdvisoryNVD20Configuration

class TestAdvisoryNVD20Configuration(unittest.TestCase):
    """AdvisoryNVD20Configuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryNVD20Configuration:
        """Test AdvisoryNVD20Configuration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryNVD20Configuration`
        """
        model = AdvisoryNVD20Configuration()
        if include_optional:
            return AdvisoryNVD20Configuration(
                negate = True,
                nodes = [
                    vulncheck_sdk.models.advisory/nvd20_node.advisory.NVD20Node(
                        cpe_match = [
                            vulncheck_sdk.models.advisory/nvd20_cvecpe_match.advisory.NVD20CVECPEMatch(
                                criteria = '', 
                                match_criteria_id = '', 
                                version_end_excluding = '', 
                                version_end_including = '', 
                                version_start_excluding = '', 
                                version_start_including = '', 
                                vulnerable = True, )
                            ], 
                        negate = True, 
                        operator = '', )
                    ],
                operator = ''
            )
        else:
            return AdvisoryNVD20Configuration(
        )
        """

    def testAdvisoryNVD20Configuration(self):
        """Test AdvisoryNVD20Configuration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
