# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_go_vuln_ranges import AdvisoryGoVulnRanges

class TestAdvisoryGoVulnRanges(unittest.TestCase):
    """AdvisoryGoVulnRanges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryGoVulnRanges:
        """Test AdvisoryGoVulnRanges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryGoVulnRanges`
        """
        model = AdvisoryGoVulnRanges()
        if include_optional:
            return AdvisoryGoVulnRanges(
                events = [
                    vulncheck_sdk.models.advisory/go_event.advisory.GoEvent(
                        fixed = '', 
                        introduced = '', )
                    ],
                type = ''
            )
        else:
            return AdvisoryGoVulnRanges(
        )
        """

    def testAdvisoryGoVulnRanges(self):
        """Test AdvisoryGoVulnRanges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
