# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_score import AdvisoryScore

class TestAdvisoryScore(unittest.TestCase):
    """AdvisoryScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryScore:
        """Test AdvisoryScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryScore`
        """
        model = AdvisoryScore()
        if include_optional:
            return AdvisoryScore(
                cve = '',
                in_kev = True,
                in_vckev = True,
                reference_urls = [
                    vulncheck_sdk.models.advisory/ref_url.advisory.RefURL(
                        date_added = '', 
                        exploit_availability = '', 
                        exploit_maturity = '', 
                        lang = '', 
                        tags = [
                            ''
                            ], 
                        url = '', )
                    ],
                score = 56
            )
        else:
            return AdvisoryScore(
        )
        """

    def testAdvisoryScore(self):
        """Test AdvisoryScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
