# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_m_branch import AdvisoryMBranch

class TestAdvisoryMBranch(unittest.TestCase):
    """AdvisoryMBranch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryMBranch:
        """Test AdvisoryMBranch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryMBranch`
        """
        model = AdvisoryMBranch()
        if include_optional:
            return AdvisoryMBranch(
                branch = [
                    vulncheck_sdk.models.advisory/m_branch.advisory.MBranch(
                        branch = [
                            vulncheck_sdk.models.advisory/m_branch.advisory.MBranch(
                                full_product_name = [
                                    vulncheck_sdk.models.advisory/m_full_product_name.advisory.MFullProductName(
                                        cpe = '', 
                                        product_id = '', 
                                        value = '', )
                                    ], 
                                items = [
                                    vulncheck_sdk.models.advisory/m_item.advisory.MItem(
                                        name = '', 
                                        product_id = '', 
                                        type = 56, 
                                        value = '', )
                                    ], 
                                name = '', 
                                type = 56, )
                            ], 
                        full_product_name = [
                            vulncheck_sdk.models.advisory/m_full_product_name.advisory.MFullProductName(
                                cpe = '', 
                                product_id = '', 
                                value = '', )
                            ], 
                        items = [
                            vulncheck_sdk.models.advisory/m_item.advisory.MItem(
                                name = '', 
                                product_id = '', 
                                type = 56, 
                                value = '', )
                            ], 
                        name = '', 
                        type = 56, )
                    ],
                full_product_name = [
                    vulncheck_sdk.models.advisory/m_full_product_name.advisory.MFullProductName(
                        cpe = '', 
                        product_id = '', 
                        value = '', )
                    ],
                items = [
                    vulncheck_sdk.models.advisory/m_item.advisory.MItem(
                        name = '', 
                        product_id = '', 
                        type = 56, 
                        value = '', )
                    ],
                name = '',
                type = 56
            )
        else:
            return AdvisoryMBranch(
        )
        """

    def testAdvisoryMBranch(self):
        """Test AdvisoryMBranch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
