# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_palo_alto_advisory import AdvisoryPaloAltoAdvisory

class TestAdvisoryPaloAltoAdvisory(unittest.TestCase):
    """AdvisoryPaloAltoAdvisory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryPaloAltoAdvisory:
        """Test AdvisoryPaloAltoAdvisory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryPaloAltoAdvisory`
        """
        model = AdvisoryPaloAltoAdvisory()
        if include_optional:
            return AdvisoryPaloAltoAdvisory(
                affected = '',
                applicable_versions = '',
                attack_complexity = '',
                attack_requirements = '',
                attack_vector = '',
                availability_impact = '',
                confidentiality_impact = '',
                cve = [
                    ''
                    ],
                cvssbase_score = '',
                date_published = '',
                date_updated = '',
                date_added = '',
                id = '',
                integrity_impact = '',
                privileges_required = '',
                problem = '',
                product = '',
                scope = '',
                severity = '',
                solution = '',
                title = '',
                unaffected = '',
                url = '',
                user_interaction = '',
                workaround = ''
            )
        else:
            return AdvisoryPaloAltoAdvisory(
        )
        """

    def testAdvisoryPaloAltoAdvisory(self):
        """Test AdvisoryPaloAltoAdvisory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
