# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_splunk import AdvisorySplunk

class TestAdvisorySplunk(unittest.TestCase):
    """AdvisorySplunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisorySplunk:
        """Test AdvisorySplunk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisorySplunk`
        """
        model = AdvisorySplunk()
        if include_optional:
            return AdvisorySplunk(
                advisory_id = '',
                affected_products = [
                    vulncheck_sdk.models.advisory/splunk_product.advisory.SplunkProduct(
                        affected_version = '', 
                        component = '', 
                        fixed_version = '', 
                        product = '', 
                        version = '', )
                    ],
                bug_id = '',
                cve = [
                    ''
                    ],
                date_added = '',
                summary = '',
                title = '',
                url = ''
            )
        else:
            return AdvisorySplunk(
        )
        """

    def testAdvisorySplunk(self):
        """Test AdvisorySplunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
