# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_m_cvss_v40 import AdvisoryMCvssV40

class TestAdvisoryMCvssV40(unittest.TestCase):
    """AdvisoryMCvssV40 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryMCvssV40:
        """Test AdvisoryMCvssV40
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryMCvssV40`
        """
        model = AdvisoryMCvssV40()
        if include_optional:
            return AdvisoryMCvssV40(
                automatable = '',
                recovery = '',
                safety = '',
                attack_complexity = '',
                attack_requirements = '',
                attack_vector = '',
                base_score = 1.337,
                base_severity = '',
                privileges_required = '',
                provider_urgency = '',
                sub_availability_impact = '',
                sub_confidentiality_impact = '',
                sub_integrity_impact = '',
                user_interaction = '',
                value_density = '',
                vector_string = '',
                version = '',
                vuln_availability_impact = '',
                vuln_confidentiality_impact = '',
                vuln_integrity_impact = '',
                vulnerability_response_effort = ''
            )
        else:
            return AdvisoryMCvssV40(
        )
        """

    def testAdvisoryMCvssV40(self):
        """Test AdvisoryMCvssV40"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
