# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_mitsubishi_electric_advisory import AdvisoryMitsubishiElectricAdvisory

class TestAdvisoryMitsubishiElectricAdvisory(unittest.TestCase):
    """AdvisoryMitsubishiElectricAdvisory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryMitsubishiElectricAdvisory:
        """Test AdvisoryMitsubishiElectricAdvisory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryMitsubishiElectricAdvisory`
        """
        model = AdvisoryMitsubishiElectricAdvisory()
        if include_optional:
            return AdvisoryMitsubishiElectricAdvisory(
                cve = [
                    ''
                    ],
                cwe = [
                    ''
                    ],
                date_added = '',
                date_last_revised = '',
                mitsubishi_electric_id = '',
                title = '',
                updated_at = '',
                url = ''
            )
        else:
            return AdvisoryMitsubishiElectricAdvisory(
        )
        """

    def testAdvisoryMitsubishiElectricAdvisory(self):
        """Test AdvisoryMitsubishiElectricAdvisory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
