# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_siemens_score import AdvisorySiemensScore

class TestAdvisorySiemensScore(unittest.TestCase):
    """AdvisorySiemensScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisorySiemensScore:
        """Test AdvisorySiemensScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisorySiemensScore`
        """
        model = AdvisorySiemensScore()
        if include_optional:
            return AdvisorySiemensScore(
                cvss_v3 = vulncheck_sdk.models.advisory/siemens_cvssv3.advisory.SiemensCVSSV3(
                    base_score = 1.337, 
                    base_severity = '', 
                    vector_string = '', 
                    version = '', ),
                products = [
                    ''
                    ]
            )
        else:
            return AdvisorySiemensScore(
        )
        """

    def testAdvisorySiemensScore(self):
        """Test AdvisorySiemensScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
