# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_alpine_linux_sec_db import AdvisoryAlpineLinuxSecDB

class TestAdvisoryAlpineLinuxSecDB(unittest.TestCase):
    """AdvisoryAlpineLinuxSecDB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryAlpineLinuxSecDB:
        """Test AdvisoryAlpineLinuxSecDB
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryAlpineLinuxSecDB`
        """
        model = AdvisoryAlpineLinuxSecDB()
        if include_optional:
            return AdvisoryAlpineLinuxSecDB(
                apkurl = '',
                archs = [
                    ''
                    ],
                cve = [
                    ''
                    ],
                date_added = '',
                distroversion = '',
                packages = [
                    vulncheck_sdk.models.advisory/alpine_linux_sec_db_package.advisory.AlpineLinuxSecDBPackage(
                        package_name = '', 
                        secfixes = [
                            vulncheck_sdk.models.advisory/alpine_linux_security_fix.advisory.AlpineLinuxSecurityFix(
                                cve = '', 
                                fixed_version = '', )
                            ], )
                    ],
                reponame = '',
                urlprefix = ''
            )
        else:
            return AdvisoryAlpineLinuxSecDB(
        )
        """

    def testAdvisoryAlpineLinuxSecDB(self):
        """Test AdvisoryAlpineLinuxSecDB"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
