# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_m_cvss_v30 import AdvisoryMCvssV30

class TestAdvisoryMCvssV30(unittest.TestCase):
    """AdvisoryMCvssV30 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryMCvssV30:
        """Test AdvisoryMCvssV30
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryMCvssV30`
        """
        model = AdvisoryMCvssV30()
        if include_optional:
            return AdvisoryMCvssV30(
                attack_complexity = '',
                attack_vector = '',
                availability_impact = '',
                base_score = 1.337,
                base_severity = '',
                confidentiality_impact = '',
                integrity_impact = '',
                privileges_required = '',
                scope = '',
                user_interaction = '',
                vector_string = '',
                version = ''
            )
        else:
            return AdvisoryMCvssV30(
        )
        """

    def testAdvisoryMCvssV30(self):
        """Test AdvisoryMCvssV30"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
