# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_ciena import AdvisoryCiena

class TestAdvisoryCiena(unittest.TestCase):
    """AdvisoryCiena unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryCiena:
        """Test AdvisoryCiena
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryCiena`
        """
        model = AdvisoryCiena()
        if include_optional:
            return AdvisoryCiena(
                cves = [
                    ''
                    ],
                date_added = '',
                issue_no = 56,
                security_advisory_number = '',
                summary = '',
                title = '',
                url = '',
                vulnerable_products = [
                    vulncheck_sdk.models.advisory/vulnerable_product.advisory.VulnerableProduct(
                        name = '', 
                        version = '', )
                    ]
            )
        else:
            return AdvisoryCiena(
        )
        """

    def testAdvisoryCiena(self):
        """Test AdvisoryCiena"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
