# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.api_temporal_metric_v3 import ApiTemporalMetricV3

class TestApiTemporalMetricV3(unittest.TestCase):
    """ApiTemporalMetricV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTemporalMetricV3:
        """Test ApiTemporalMetricV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTemporalMetricV3`
        """
        model = ApiTemporalMetricV3()
        if include_optional:
            return ApiTemporalMetricV3(
                cvss_v3 = vulncheck_sdk.models.api/temporal_cvssv3.api.TemporalCVSSV3(
                    exploit_code_maturity = '', 
                    remediation_level = '', 
                    report_confidence = '', 
                    temporal_score = 1.337, 
                    vector_string = '', 
                    version = '', )
            )
        else:
            return ApiTemporalMetricV3(
        )
        """

    def testApiTemporalMetricV3(self):
        """Test ApiTemporalMetricV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
