# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.api_nvd20_cpe_match import ApiNVD20CPEMatch

class TestApiNVD20CPEMatch(unittest.TestCase):
    """ApiNVD20CPEMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiNVD20CPEMatch:
        """Test ApiNVD20CPEMatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiNVD20CPEMatch`
        """
        model = ApiNVD20CPEMatch()
        if include_optional:
            return ApiNVD20CPEMatch(
                cpe_last_modified = '',
                created = '',
                criteria = '',
                last_modified = '',
                match_criteria_id = '',
                matches = [
                    vulncheck_sdk.models.api/nvd20_cpe_name.api.NVD20CPEName(
                        cpe_name = '', 
                        cpe_name_id = '', )
                    ],
                status = '',
                version_end_excluding = '',
                version_end_including = '',
                version_start_excluding = '',
                version_start_including = ''
            )
        else:
            return ApiNVD20CPEMatch(
        )
        """

    def testApiNVD20CPEMatch(self):
        """Test ApiNVD20CPEMatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
