# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.api_nvd20_metric import ApiNVD20Metric

class TestApiNVD20Metric(unittest.TestCase):
    """ApiNVD20Metric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiNVD20Metric:
        """Test ApiNVD20Metric
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiNVD20Metric`
        """
        model = ApiNVD20Metric()
        if include_optional:
            return ApiNVD20Metric(
                cvss_metric_v2 = [
                    vulncheck_sdk.models.api/nvd20_cvss_metric_v2.api.NVD20CvssMetricV2(
                        ac_insuf_info = True, 
                        base_severity = '', 
                        cvss_data = vulncheck_sdk.models.api/nvd20_cvss_data_v2.api.NVD20CvssDataV2(
                            access_complexity = '', 
                            access_vector = '', 
                            authentication = '', 
                            availability_impact = '', 
                            availability_requirement = '', 
                            base_score = 1.337, 
                            collateral_damage_potential = '', 
                            confidentiality_impact = '', 
                            confidentiality_requirement = '', 
                            environmental_score = 1.337, 
                            exploitability = '', 
                            integrity_impact = '', 
                            integrity_requirement = '', 
                            remediation_level = '', 
                            report_confidence = '', 
                            target_distribution = '', 
                            temporal_score = 1.337, 
                            vector_string = '', 
                            version = '', ), 
                        exploitability_score = 1.337, 
                        impact_score = 1.337, 
                        obtain_all_privilege = True, 
                        obtain_other_privilege = True, 
                        obtain_user_privilege = True, 
                        source = '', 
                        type = '', 
                        user_interaction_required = True, )
                    ],
                cvss_metric_v30 = [
                    vulncheck_sdk.models.api/nvd20_cvss_metric_v3.api.NVD20CvssMetricV3(
                        cvss_data = vulncheck_sdk.models.api/nvd20_cvss_data_v3.api.NVD20CvssDataV3(
                            attack_complexity = '', 
                            attack_vector = '', 
                            availability_impact = '', 
                            availability_requirement = '', 
                            base_score = 1.337, 
                            base_severity = '', 
                            confidentiality_impact = '', 
                            confidentiality_requirement = '', 
                            environmental_score = 1.337, 
                            environmental_severity = '', 
                            exploit_code_maturity = '', 
                            integrity_impact = '', 
                            integrity_requirement = '', 
                            modified_attack_complexity = '', 
                            modified_attack_vector = '', 
                            modified_availability_impact = '', 
                            modified_confidentiality_impact = '', 
                            modified_integrity_impact = '', 
                            modified_privileges_required = '', 
                            modified_scope = '', 
                            modified_user_interaction = '', 
                            privileges_required = '', 
                            remediation_level = '', 
                            report_confidence = '', 
                            scope = '', 
                            temporal_score = 1.337, 
                            temporal_severity = '', 
                            user_interaction = '', 
                            vector_string = '', 
                            version = '', ), 
                        exploitability_score = 1.337, 
                        impact_score = 1.337, 
                        source = '', 
                        type = '', )
                    ],
                cvss_metric_v31 = [
                    vulncheck_sdk.models.api/nvd20_cvss_metric_v3.api.NVD20CvssMetricV3(
                        cvss_data = vulncheck_sdk.models.api/nvd20_cvss_data_v3.api.NVD20CvssDataV3(
                            attack_complexity = '', 
                            attack_vector = '', 
                            availability_impact = '', 
                            availability_requirement = '', 
                            base_score = 1.337, 
                            base_severity = '', 
                            confidentiality_impact = '', 
                            confidentiality_requirement = '', 
                            environmental_score = 1.337, 
                            environmental_severity = '', 
                            exploit_code_maturity = '', 
                            integrity_impact = '', 
                            integrity_requirement = '', 
                            modified_attack_complexity = '', 
                            modified_attack_vector = '', 
                            modified_availability_impact = '', 
                            modified_confidentiality_impact = '', 
                            modified_integrity_impact = '', 
                            modified_privileges_required = '', 
                            modified_scope = '', 
                            modified_user_interaction = '', 
                            privileges_required = '', 
                            remediation_level = '', 
                            report_confidence = '', 
                            scope = '', 
                            temporal_score = 1.337, 
                            temporal_severity = '', 
                            user_interaction = '', 
                            vector_string = '', 
                            version = '', ), 
                        exploitability_score = 1.337, 
                        impact_score = 1.337, 
                        source = '', 
                        type = '', )
                    ],
                cvss_metric_v40 = [
                    vulncheck_sdk.models.api/nvd20_cvss_metric_v40.api.NVD20CvssMetricV40(
                        cvss_data = vulncheck_sdk.models.advisory/cvssv40.advisory.CVSSV40(
                            automatable = '', 
                            recovery = '', 
                            safety = '', 
                            attack_complexity = '', 
                            attack_requirements = '', 
                            attack_vector = '', 
                            availability_requirement = '', 
                            base_score = 1.337, 
                            base_severity = '', 
                            confidentiality_requirement = '', 
                            exploit_maturity = '', 
                            integrity_requirement = '', 
                            modified_attack_complexity = '', 
                            modified_attack_requirements = '', 
                            modified_attack_vector = '', 
                            modified_privileges_required = '', 
                            modified_sub_availability_impact = '', 
                            modified_sub_confidentiality_impact = '', 
                            modified_sub_integrity_impact = '', 
                            modified_user_interaction = '', 
                            modified_vuln_availability_impact = '', 
                            modified_vuln_confidentiality_impact = '', 
                            modified_vuln_integrity_impact = '', 
                            privileges_required = '', 
                            provider_urgency = '', 
                            sub_availability_impact = '', 
                            sub_confidentiality_impact = '', 
                            sub_integrity_impact = '', 
                            user_interaction = '', 
                            value_density = '', 
                            vector_string = '', 
                            version = '', 
                            vuln_availability_impact = '', 
                            vuln_confidentiality_impact = '', 
                            vuln_integrity_impact = '', 
                            vulnerability_response_effort = '', ), 
                        source = '', 
                        type = '', )
                    ]
            )
        else:
            return ApiNVD20Metric(
        )
        """

    def testApiNVD20Metric(self):
        """Test ApiNVD20Metric"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
