# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_enisa_id_product import AdvisoryEnisaIDProduct

class TestAdvisoryEnisaIDProduct(unittest.TestCase):
    """AdvisoryEnisaIDProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryEnisaIDProduct:
        """Test AdvisoryEnisaIDProduct
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryEnisaIDProduct`
        """
        model = AdvisoryEnisaIDProduct()
        if include_optional:
            return AdvisoryEnisaIDProduct(
                id = '',
                product_name = '',
                product_version = ''
            )
        else:
            return AdvisoryEnisaIDProduct(
        )
        """

    def testAdvisoryEnisaIDProduct(self):
        """Test AdvisoryEnisaIDProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
