# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vulncheck_sdk.models.advisory_malicious_vs_code_discovery import AdvisoryMaliciousVSCodeDiscovery
from typing import Optional, Set
from typing_extensions import Self

class AdvisoryMaliciousVSCodeExts(BaseModel):
    """
    advisory.MaliciousVSCodeExts
    """ # noqa: E501
    discoveries: Optional[List[AdvisoryMaliciousVSCodeDiscovery]] = Field(default=None, description="Discoveries list of individual vulnerability reports, sorted chronologically by discovery date")
    first_seen: Optional[StrictStr] = Field(default=None, description="FirstSeen the earliest date the vulnerability was observed or created in our system")
    last_updated: Optional[StrictStr] = Field(default=None, description="LastUpdated the most recent date when any discovery was added for this extension")
    marketplace: Optional[List[StrictStr]] = Field(default=None, description="Marketplace list of names of the marketplaces where the extension versions are available")
    name: Optional[StrictStr] = Field(default=None, description="Name is the name of the extension")
    publisher: Optional[StrictStr] = Field(default=None, description="Publisher name of the publisher of the extension")
    references: Optional[List[StrictStr]] = Field(default=None, description="Reference list of locations where the public releases about the vulnerabilities were pulled")
    types: Optional[List[StrictStr]] = Field(default=None, description="Types VulnCheck vulnerability classifications found for this extension")
    versions: Optional[List[StrictStr]] = Field(default=None, description="Versions list of vulnerable versions")
    __properties: ClassVar[List[str]] = ["discoveries", "first_seen", "last_updated", "marketplace", "name", "publisher", "references", "types", "versions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdvisoryMaliciousVSCodeExts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in discoveries (list)
        _items = []
        if self.discoveries:
            for _item_discoveries in self.discoveries:
                if _item_discoveries:
                    _items.append(_item_discoveries.to_dict())
            _dict['discoveries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdvisoryMaliciousVSCodeExts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "discoveries": [AdvisoryMaliciousVSCodeDiscovery.from_dict(_item) for _item in obj["discoveries"]] if obj.get("discoveries") is not None else None,
            "first_seen": obj.get("first_seen"),
            "last_updated": obj.get("last_updated"),
            "marketplace": obj.get("marketplace"),
            "name": obj.get("name"),
            "publisher": obj.get("publisher"),
            "references": obj.get("references"),
            "types": obj.get("types"),
            "versions": obj.get("versions")
        })
        return _obj


