# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vulncheck_sdk.models.api_nvd20_ssvc_decision_point_child import ApiNVD20SsvcDecisionPointChild
from vulncheck_sdk.models.api_nvd20_ssvc_decision_point_option import ApiNVD20SsvcDecisionPointOption
from typing import Optional, Set
from typing_extensions import Self

class ApiNVD20SsvcDecisionPoint(BaseModel):
    """
    api.NVD20SsvcDecisionPoint
    """ # noqa: E501
    children: Optional[List[ApiNVD20SsvcDecisionPointChild]] = None
    decision_type: Optional[StrictStr] = None
    key: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    options: Optional[List[ApiNVD20SsvcDecisionPointOption]] = None
    __properties: ClassVar[List[str]] = ["children", "decision_type", "key", "label", "options"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiNVD20SsvcDecisionPoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiNVD20SsvcDecisionPoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "children": [ApiNVD20SsvcDecisionPointChild.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "decision_type": obj.get("decision_type"),
            "key": obj.get("key"),
            "label": obj.get("label"),
            "options": [ApiNVD20SsvcDecisionPointOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None
        })
        return _obj


