# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_comm_vault import AdvisoryCommVault

class TestAdvisoryCommVault(unittest.TestCase):
    """AdvisoryCommVault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryCommVault:
        """Test AdvisoryCommVault
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryCommVault`
        """
        model = AdvisoryCommVault()
        if include_optional:
            return AdvisoryCommVault(
                cve = [
                    ''
                    ],
                cve_details = [
                    vulncheck_sdk.models.advisory/comm_vault_cve_details.advisory.CommVaultCVEDetails(
                        cve_id = '', 
                        cvss = '', 
                        description = '', 
                        external_links = [
                            ''
                            ], )
                    ],
                cvss_range = '',
                date_added = '',
                description = '',
                id = '',
                impacted_product = vulncheck_sdk.models.advisory/comm_vault_impacted_product.advisory.CommVaultImpactedProduct(
                    description = '', 
                    impacted_product_details = [
                        vulncheck_sdk.models.advisory/comm_vault_impacted_product_details.advisory.CommVaultImpactedProductDetails(
                            affected_versions = '', 
                            platforms = [
                                ''
                                ], 
                            product_name = '', 
                            resolved_versions = '', 
                            status = '', )
                        ], ),
                references = [
                    ''
                    ],
                resolution = vulncheck_sdk.models.advisory/comm_vault_resolution.advisory.CommVaultResolution(
                    description = '', 
                    resolution_details = [
                        vulncheck_sdk.models.advisory/comm_vault_resolution_details.advisory.CommVaultResolutionDetails(
                            feature_release = '', 
                            maintenance_release = '', )
                        ], ),
                severity = '',
                title = '',
                updated_at = '',
                url = ''
            )
        else:
            return AdvisoryCommVault(
        )
        """

    def testAdvisoryCommVault(self):
        """Test AdvisoryCommVault"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
