# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_csaf_score import AdvisoryCSAFScore

class TestAdvisoryCSAFScore(unittest.TestCase):
    """AdvisoryCSAFScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryCSAFScore:
        """Test AdvisoryCSAFScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryCSAFScore`
        """
        model = AdvisoryCSAFScore()
        if include_optional:
            return AdvisoryCSAFScore(
                cvss_v2 = vulncheck_sdk.models.advisory/cvssv2.advisory.CVSSV2(
                    access_complexity = '', 
                    access_vector = '', 
                    authentication = '', 
                    availability_impact = '', 
                    availability_requirement = '', 
                    base_score = 1.337, 
                    collateral_damage_potential = '', 
                    confidentiality_impact = '', 
                    confidentiality_requirement = '', 
                    environmental_score = 1.337, 
                    exploitability = '', 
                    integrity_impact = '', 
                    integrity_requirement = '', 
                    remediation_level = '', 
                    report_confidence = '', 
                    target_distribution = '', 
                    temporal_score = 1.337, ),
                cvss_v3 = vulncheck_sdk.models.advisory/cvssv3.advisory.CVSSV3(
                    attack_complexity = '', 
                    attack_vector = '', 
                    availability_impact = '', 
                    base_score = 1.337, 
                    base_severity = '', 
                    confidentiality_impact = '', 
                    integrity_impact = '', 
                    privileges_required = '', 
                    scope = '', 
                    user_interaction = '', 
                    vector_string = '', 
                    version = '', ),
                products = [
                    ''
                    ]
            )
        else:
            return AdvisoryCSAFScore(
        )
        """

    def testAdvisoryCSAFScore(self):
        """Test AdvisoryCSAFScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
