# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.render_response_with_metadata_array_advisory_end_of_life_paginate_pagination import RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination

class TestRenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination(unittest.TestCase):
    """RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination:
        """Test RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination`
        """
        model = RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination()
        if include_optional:
            return RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination(
                benchmark = 1.337,
                meta = vulncheck_sdk.models.paginate/pagination.paginate.Pagination(
                    cursor = '', 
                    first_item = 56, 
                    index = '', 
                    last_item = 56, 
                    limit = 56, 
                    matches = [
                        vulncheck_sdk.models.paginate/match.paginate.Match(
                            field = '', 
                            value = '', )
                        ], 
                    max_pages = 56, 
                    next_cursor = '', 
                    opensearch_query = vulncheck_sdk.models.opensearch_query.opensearch_query(), 
                    order = '', 
                    page = 56, 
                    pages = [
                        ''
                        ], 
                    parameters = [
                        vulncheck_sdk.models.paginate/param.paginate.Param(
                            filtering = '', 
                            format = '', 
                            name = '', )
                        ], 
                    show_pages = True, 
                    show_query = True, 
                    sort = '', 
                    timestamp = '', 
                    total_documents = 56, 
                    total_pages = 56, 
                    warnings = [
                        ''
                        ], ),
                data = [
                    vulncheck_sdk.models.advisory/end_of_life.advisory.EndOfLife(
                        cve = [
                            ''
                            ], 
                        cycles = [
                            vulncheck_sdk.models.advisory/cycle.advisory.Cycle(
                                codename = '', 
                                cycle = '', 
                                discontinued = vulncheck_sdk.models.discontinued.discontinued(), 
                                eol = vulncheck_sdk.models.eol.eol(), 
                                extended_support = vulncheck_sdk.models.extended_support.extendedSupport(), 
                                latest = '', 
                                latest_release_date = '', 
                                link = '', 
                                lts = vulncheck_sdk.models.lts.lts(), 
                                release_date = '', 
                                release_label = '', 
                                support = vulncheck_sdk.models.support.support(), )
                            ], 
                        date_added = '', 
                        name = '', 
                        url = '', )
                    ]
            )
        else:
            return RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination(
        )
        """

    def testRenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination(self):
        """Test RenderResponseWithMetadataArrayAdvisoryEndOfLifePaginatePagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
