# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.api.backup_api import BackupApi


class TestBackupApi(unittest.TestCase):
    """BackupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackupApi()

    def tearDown(self) -> None:
        pass

    def test_backup_get(self) -> None:
        """Test case for backup_get

        List available backups
        """
        pass

    def test_backup_index_get(self) -> None:
        """Test case for backup_index_get

        Get backup by feed name
        """
        pass


if __name__ == '__main__':
    unittest.main()
