# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_mediatek import AdvisoryMediatek

class TestAdvisoryMediatek(unittest.TestCase):
    """AdvisoryMediatek unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryMediatek:
        """Test AdvisoryMediatek
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryMediatek`
        """
        model = AdvisoryMediatek()
        if include_optional:
            return AdvisoryMediatek(
                affected_chipsets = [
                    ''
                    ],
                affected_software = [
                    ''
                    ],
                cve = [
                    ''
                    ],
                date_added = '',
                description = '',
                severity = '',
                title = '',
                updated_at = '',
                url = ''
            )
        else:
            return AdvisoryMediatek(
        )
        """

    def testAdvisoryMediatek(self):
        """Test AdvisoryMediatek"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
