# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.render_response_with_metadata_array_advisory_alma_linux_update_paginate_pagination import RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination

class TestRenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination(unittest.TestCase):
    """RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination:
        """Test RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination`
        """
        model = RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination()
        if include_optional:
            return RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination(
                benchmark = 1.337,
                meta = vulncheck_sdk.models.paginate/pagination.paginate.Pagination(
                    cursor = '', 
                    first_item = 56, 
                    index = '', 
                    last_item = 56, 
                    limit = 56, 
                    matches = [
                        vulncheck_sdk.models.paginate/match.paginate.Match(
                            field = '', 
                            value = '', )
                        ], 
                    max_pages = 56, 
                    next_cursor = '', 
                    opensearch_query = vulncheck_sdk.models.opensearch_query.opensearch_query(), 
                    order = '', 
                    page = 56, 
                    pages = [
                        ''
                        ], 
                    parameters = [
                        vulncheck_sdk.models.paginate/param.paginate.Param(
                            filtering = '', 
                            format = '', 
                            name = '', )
                        ], 
                    show_pages = True, 
                    show_query = True, 
                    sort = '', 
                    timestamp = '', 
                    total_documents = 56, 
                    total_pages = 56, 
                    warnings = [
                        ''
                        ], ),
                data = [
                    vulncheck_sdk.models.advisory/alma_linux_update.advisory.AlmaLinuxUpdate(
                        bs_repo_id = vulncheck_sdk.models.advisory/alma_object_id.advisory.AlmaObjectID(
                            __oid = '', ), 
                        cve = [
                            ''
                            ], 
                        date_added = '', 
                        description = '', 
                        fromstr = '', 
                        id = vulncheck_sdk.models.advisory/alma_object_id.advisory.AlmaObjectID(
                            __oid = '', ), 
                        issued_date = vulncheck_sdk.models.advisory/alma_date.advisory.AlmaDate(
                            __date = 56, ), 
                        pkglist = vulncheck_sdk.models.advisory/alma_package_list.advisory.AlmaPackageList(
                            name = '', 
                            packages = [
                                vulncheck_sdk.models.advisory/alma_package.advisory.AlmaPackage(
                                    arch = '', 
                                    epoch = '', 
                                    filename = '', 
                                    name = '', 
                                    reboot_suggested = 56, 
                                    release = '', 
                                    source = '', 
                                    sum = '', 
                                    version = '', )
                                ], 
                            shortname = '', ), 
                        pushcount = '', 
                        references = [
                            vulncheck_sdk.models.advisory/alma_reference.advisory.AlmaReference(
                                href = '', 
                                title = '', 
                                type = '', )
                            ], 
                        release = '', 
                        rights = '', 
                        severity = '', 
                        solution = '', 
                        status = '', 
                        summary = '', 
                        title = '', 
                        type = '', 
                        update_url = '', 
                        updated_date = vulncheck_sdk.models.advisory/alma_date.advisory.AlmaDate(
                            __date = 56, ), 
                        updateinfo_id = '', 
                        version = '', )
                    ]
            )
        else:
            return RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination(
        )
        """

    def testRenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination(self):
        """Test RenderResponseWithMetadataArrayAdvisoryAlmaLinuxUpdatePaginatePagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
