# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_alma_date import AdvisoryAlmaDate

class TestAdvisoryAlmaDate(unittest.TestCase):
    """AdvisoryAlmaDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryAlmaDate:
        """Test AdvisoryAlmaDate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryAlmaDate`
        """
        model = AdvisoryAlmaDate()
        if include_optional:
            return AdvisoryAlmaDate(
                var_date = 56
            )
        else:
            return AdvisoryAlmaDate(
        )
        """

    def testAdvisoryAlmaDate(self):
        """Test AdvisoryAlmaDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
