# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_mozilla_advisory import AdvisoryMozillaAdvisory

class TestAdvisoryMozillaAdvisory(unittest.TestCase):
    """AdvisoryMozillaAdvisory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryMozillaAdvisory:
        """Test AdvisoryMozillaAdvisory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryMozillaAdvisory`
        """
        model = AdvisoryMozillaAdvisory()
        if include_optional:
            return AdvisoryMozillaAdvisory(
                affected_components = [
                    vulncheck_sdk.models.advisory/mozilla_component.advisory.MozillaComponent(
                        bugzilla = [
                            ''
                            ], 
                        cve = [
                            ''
                            ], 
                        description = '', 
                        impact = '', 
                        reporter = '', 
                        title = '', )
                    ],
                bugzilla = [
                    ''
                    ],
                cve = [
                    ''
                    ],
                date_added = '',
                description = '',
                fixed_in = [
                    ''
                    ],
                impact = '',
                products = [
                    ''
                    ],
                reporter = '',
                risk = '',
                title = '',
                url = ''
            )
        else:
            return AdvisoryMozillaAdvisory(
        )
        """

    def testAdvisoryMozillaAdvisory(self):
        """Test AdvisoryMozillaAdvisory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
