# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.api.advisory_api import AdvisoryApi


class TestAdvisoryApi(unittest.TestCase):
    """AdvisoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdvisoryApi()

    def tearDown(self) -> None:
        pass

    def test_advisory_get(self) -> None:
        """Test case for advisory_get

        Query advisories
        """
        pass

    def test_advisory_list_get(self) -> None:
        """Test case for advisory_list_get

        List advisory feeds
        """
        pass


if __name__ == '__main__':
    unittest.main()
