# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.advisory_generic_eol_core import AdvisoryGenericEOLCore

class TestAdvisoryGenericEOLCore(unittest.TestCase):
    """AdvisoryGenericEOLCore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryGenericEOLCore:
        """Test AdvisoryGenericEOLCore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryGenericEOLCore`
        """
        model = AdvisoryGenericEOLCore()
        if include_optional:
            return AdvisoryGenericEOLCore(
                end_of_life = '',
                end_of_sales = '',
                end_of_security_support = '',
                last_updated = ''
            )
        else:
            return AdvisoryGenericEOLCore(
        )
        """

    def testAdvisoryGenericEOLCore(self):
        """Test AdvisoryGenericEOLCore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
