# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.models.render_response_with_metadata_array_api_target_intel_paginate_pagination import RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination

class TestRenderResponseWithMetadataArrayApiTargetIntelPaginatePagination(unittest.TestCase):
    """RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination:
        """Test RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination`
        """
        model = RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination()
        if include_optional:
            return RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination(
                benchmark = 1.337,
                meta = vulncheck_sdk.models.paginate/pagination.paginate.Pagination(
                    cursor = '', 
                    first_item = 56, 
                    index = '', 
                    last_item = 56, 
                    limit = 56, 
                    matches = [
                        vulncheck_sdk.models.paginate/match.paginate.Match(
                            field = '', 
                            value = '', )
                        ], 
                    max_pages = 56, 
                    next_cursor = '', 
                    opensearch_query = vulncheck_sdk.models.opensearch_query.opensearch_query(), 
                    order = '', 
                    page = 56, 
                    pages = [
                        ''
                        ], 
                    parameters = [
                        vulncheck_sdk.models.paginate/param.paginate.Param(
                            filtering = '', 
                            format = '', 
                            name = '', )
                        ], 
                    show_pages = True, 
                    show_query = True, 
                    sort = '', 
                    timestamp = '', 
                    total_documents = 56, 
                    total_pages = 56, 
                    warnings = [
                        ''
                        ], ),
                data = [
                    vulncheck_sdk.models.api/target_intel.api.TargetIntel(
                        _timestamp = '', 
                        as_domain = '', 
                        as_name = '', 
                        asn = '', 
                        confidence = 1.337, 
                        country = '', 
                        country_code = '', 
                        cpe = '', 
                        cves = [
                            ''
                            ], 
                        date_added = '', 
                        fingerprint_metadata = [
                            56
                            ], 
                        ip = '', 
                        match_target = '', 
                        port = 56, 
                        product = '', 
                        protocol = '', 
                        rule_id = '', 
                        rule_source = '', 
                        service_metadata = [
                            56
                            ], 
                        type = '', 
                        vendor = '', 
                        version = '', )
                    ]
            )
        else:
            return RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination(
        )
        """

    def testRenderResponseWithMetadataArrayApiTargetIntelPaginatePagination(self):
        """Test RenderResponseWithMetadataArrayApiTargetIntelPaginatePagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
