# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.aio.models.render_response_with_metadata_array_advisory_meta_advisories_paginate_pagination import RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination

class TestRenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination(unittest.TestCase):
    """RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination:
        """Test RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination`
        """
        model = RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination()
        if include_optional:
            return RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination(
                benchmark = 1.337,
                meta = vulncheck_sdk.aio.models.paginate/pagination.paginate.Pagination(
                    cursor = '', 
                    first_item = 56, 
                    index = '', 
                    last_item = 56, 
                    limit = 56, 
                    matches = [
                        vulncheck_sdk.aio.models.paginate/match.paginate.Match(
                            field = '', 
                            value = '', )
                        ], 
                    max_pages = 56, 
                    next_cursor = '', 
                    opensearch_query = vulncheck_sdk.aio.models.opensearch_query.opensearch_query(), 
                    order = '', 
                    page = 56, 
                    pages = [
                        ''
                        ], 
                    parameters = [
                        vulncheck_sdk.aio.models.paginate/param.paginate.Param(
                            filtering = '', 
                            format = '', 
                            name = '', )
                        ], 
                    show_pages = True, 
                    show_query = True, 
                    sort = '', 
                    timestamp = '', 
                    total_documents = 56, 
                    total_pages = 56, 
                    warnings = [
                        ''
                        ], ),
                data = [
                    vulncheck_sdk.aio.models.advisory/meta_advisories.advisory.MetaAdvisories(
                        affected = [
                            vulncheck_sdk.aio.models.advisory/m_affected.advisory.MAffected(
                                collection_url = '', 
                                cpes = [
                                    ''
                                    ], 
                                default_status = '', 
                                package_name = '', 
                                package_url = '', 
                                platforms = [
                                    ''
                                    ], 
                                product = '', 
                                repo = '', 
                                vendor = '', 
                                versions = [
                                    vulncheck_sdk.aio.models.advisory/m_version.advisory.MVersion(
                                        less_than = '', 
                                        less_than_or_equal = '', 
                                        status = '', 
                                        version = '', 
                                        version_type = '', )
                                    ], )
                            ], 
                        cve = [
                            ''
                            ], 
                        date_added = '', 
                        references = [
                            ''
                            ], 
                        summary = '', 
                        updated_at = '', 
                        url = '', )
                    ]
            )
        else:
            return RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination(
        )
        """

    def testRenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination(self):
        """Test RenderResponseWithMetadataArrayAdvisoryMetaAdvisoriesPaginatePagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
