# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.aio.models.advisory_ioc_threat_actor_advisory import AdvisoryIOCThreatActorAdvisory

class TestAdvisoryIOCThreatActorAdvisory(unittest.TestCase):
    """AdvisoryIOCThreatActorAdvisory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvisoryIOCThreatActorAdvisory:
        """Test AdvisoryIOCThreatActorAdvisory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvisoryIOCThreatActorAdvisory`
        """
        model = AdvisoryIOCThreatActorAdvisory()
        if include_optional:
            return AdvisoryIOCThreatActorAdvisory(
                cve = [
                    ''
                    ],
                date_added = '',
                malicious_domains = [
                    ''
                    ],
                malicious_files = [
                    vulncheck_sdk.aio.models.advisory/ioc_file.advisory.IOCFile(
                        name = '', 
                        sha256 = '', )
                    ],
                malicious_ip = [
                    ''
                    ],
                references = [
                    ''
                    ],
                threat_actor_name = '',
                title = '',
                updated_at = '',
                url = ''
            )
        else:
            return AdvisoryIOCThreatActorAdvisory(
        )
        """

    def testAdvisoryIOCThreatActorAdvisory(self):
        """Test AdvisoryIOCThreatActorAdvisory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
