# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.aio.models.api_nvd20_ssvc_option import ApiNVD20SsvcOption

class TestApiNVD20SsvcOption(unittest.TestCase):
    """ApiNVD20SsvcOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiNVD20SsvcOption:
        """Test ApiNVD20SsvcOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiNVD20SsvcOption`
        """
        model = ApiNVD20SsvcOption()
        if include_optional:
            return ApiNVD20SsvcOption(
                automatable = '',
                exploitation = '',
                technical_impact = ''
            )
        else:
            return ApiNVD20SsvcOption(
        )
        """

    def testApiNVD20SsvcOption(self):
        """Test ApiNVD20SsvcOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
