# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.aio.models.api_nvd20_change import ApiNVD20Change

class TestApiNVD20Change(unittest.TestCase):
    """ApiNVD20Change unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiNVD20Change:
        """Test ApiNVD20Change
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiNVD20Change`
        """
        model = ApiNVD20Change()
        if include_optional:
            return ApiNVD20Change(
                created = '',
                cve_change_id = '',
                cve_id = '',
                details = [
                    vulncheck_sdk.aio.models.api/nvd20_details_extended.api.NVD20DetailsExtended(
                        action = '', 
                        new_cwes = [
                            ''
                            ], 
                        new_types = [
                            ''
                            ], 
                        new_url = '', 
                        new_value = null, 
                        old_cwes = [
                            ''
                            ], 
                        old_types = [
                            ''
                            ], 
                        old_url = '', 
                        old_value = null, 
                        type = '', )
                    ],
                event_name = '',
                source_identifier = ''
            )
        else:
            return ApiNVD20Change(
        )
        """

    def testApiNVD20Change(self):
        """Test ApiNVD20Change"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
