# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vulncheck_sdk.aio.models.api_cve_confirmed import ApiCVEConfirmed

class TestApiCVEConfirmed(unittest.TestCase):
    """ApiCVEConfirmed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiCVEConfirmed:
        """Test ApiCVEConfirmed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiCVEConfirmed`
        """
        model = ApiCVEConfirmed()
        if include_optional:
            return ApiCVEConfirmed(
                confirmed = True,
                cve_id = ''
            )
        else:
            return ApiCVEConfirmed(
        )
        """

    def testApiCVEConfirmed(self):
        """Test ApiCVEConfirmed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
