# coding: utf-8

"""
    VulnCheck API

    VulnCheck API (v3 + v4)

    The version of the OpenAPI document: latest
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vulncheck_sdk.aio.models.advisory_ioc_file import AdvisoryIOCFile
from typing import Optional, Set
from typing_extensions import Self

class AdvisoryIOCRansomwareAdvisory(BaseModel):
    """
    advisory.IOCRansomwareAdvisory
    """ # noqa: E501
    cve: Optional[List[StrictStr]] = None
    date_added: Optional[StrictStr] = None
    malicious_domains: Optional[List[StrictStr]] = None
    malicious_files: Optional[List[AdvisoryIOCFile]] = None
    malicious_ip: Optional[List[StrictStr]] = None
    ransomware_name: Optional[StrictStr] = None
    references: Optional[List[StrictStr]] = None
    title: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["cve", "date_added", "malicious_domains", "malicious_files", "malicious_ip", "ransomware_name", "references", "title", "updated_at", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdvisoryIOCRansomwareAdvisory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in malicious_files (list)
        _items = []
        if self.malicious_files:
            for _item_malicious_files in self.malicious_files:
                if _item_malicious_files:
                    _items.append(_item_malicious_files.to_dict())
            _dict['malicious_files'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdvisoryIOCRansomwareAdvisory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cve": obj.get("cve"),
            "date_added": obj.get("date_added"),
            "malicious_domains": obj.get("malicious_domains"),
            "malicious_files": [AdvisoryIOCFile.from_dict(_item) for _item in obj["malicious_files"]] if obj.get("malicious_files") is not None else None,
            "malicious_ip": obj.get("malicious_ip"),
            "ransomware_name": obj.get("ransomware_name"),
            "references": obj.get("references"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at"),
            "url": obj.get("url")
        })
        return _obj


