# coding: utf-8

"""
    VulnCheck API

    Version 3 of the VulnCheck API

    The version of the OpenAPI document: 3.0
    Contact: support@vulncheck.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vulncheck_sdk.aio.models.api_mitre_d3fend_technique import ApiMitreD3fendTechnique
from typing import Optional, Set
from typing_extensions import Self

class ApiMitreMitigation2D3fendMapping(BaseModel):
    """
    ApiMitreMitigation2D3fendMapping
    """ # noqa: E501
    d3fendtechniques: Optional[List[ApiMitreD3fendTechnique]] = None
    id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["d3fendtechniques", "id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiMitreMitigation2D3fendMapping from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in d3fendtechniques (list)
        _items = []
        if self.d3fendtechniques:
            for _item_d3fendtechniques in self.d3fendtechniques:
                if _item_d3fendtechniques:
                    _items.append(_item_d3fendtechniques.to_dict())
            _dict['d3fendtechniques'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiMitreMitigation2D3fendMapping from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "d3fendtechniques": [ApiMitreD3fendTechnique.from_dict(_item) for _item in obj["d3fendtechniques"]] if obj.get("d3fendtechniques") is not None else None,
            "id": obj.get("id")
        })
        return _obj


